apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops
type: Opaque
stringData:
  # PostgreSQL Credentials
  POSTGRES_USER: mlops
  POSTGRES_PASSWORD: mlops_secure_pass_change_me
  POSTGRES_DB: mlops

  # Redis Password
  REDIS_PASSWORD: redis_pass_change_me

  # MinIO Credentials
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin123_change_me

  # MLFlow Credentials
  MLFLOW_TRACKING_USERNAME: admin
  MLFLOW_TRACKING_PASSWORD: mlflow_pass_change_me

  # Airflow Credentials
  AIRFLOW_ADMIN_USER: admin
  AIRFLOW_ADMIN_PASSWORD: airflow_pass_change_me
  AIRFLOW_FERNET_KEY: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=

  # AWS Credentials (for S3)
  AWS_ACCESS_KEY_ID: your_access_key
  AWS_SECRET_ACCESS_KEY: your_secret_key
